<?php

use think\migration\Migrator;
use think\migration\db\Column;

class Systems extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
        $table=$this->table('systems',['collation'=>'utf8_unicode_ci']);
        $table->addColumn('key','string',['comment'=>'系统名称'])
            ->addColumn('value','string',['comment'=>'系统内容'])
            ->addTimestamps()
            ->addSoftDelete()
            ->addIndex(['key'])
            ->create();

    }
    public function up()
    {
        parent::up(); // TODO: Change the autogenerated stub
    }
    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
