<?php

use think\migration\Migrator;
use think\migration\db\Column;
use Phinx\Db\Adapter\MysqlAdapter;

class Categories extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */

    /**
     * Migrate Change
     * Version
     * Creator By River
     * 2018-09-20 18:19:19
     */
    public function change()
    {
        //Create the table
        $table=$this->table('categories',['collation'=>'utf8_unicode_ci']);
        $table->addColumn('parent_id','integer',['default'=>0,'limit'=>11,'comment'=>'分类父级id'])
            ->addColumn('lft','integer',['limit'=>11,'comment'=>'分类左值'])
            ->addColumn('rgt','integer',['limit'=>11,'comment'=>'分类右值'])
            ->addColumn('depth','integer',['limit'=>11,'comment'=>'分类深度，可能会用到'])
            ->addColumn('name','string',['default'=>'','comment'=>'分类名称'])
            ->addTimestamps()
            ->addSoftDelete()
            ->addIndex(['name','lft','rgt'])
            ->create();

    }

    /**
     * Migrate Up
     * Version 1.0
     * Creator By River
     * 2018-09-20 18:17:25
     */
    public function up()
    {
        parent::up(); // TODO: Change the autogenerated stub
    }

    /**
     * Migrate Down
     * Version 1.0
     * Creator By River
     * 2018-09-20 18:18:27
     */
    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
