<?php

use think\migration\Migrator;
use think\migration\db\Column;

class Navigations extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
        $table=$this->table('navigations',['collation'=>'utf8_unicode_ci']);
        $table->addColumn('name','string',['comment'=>'导航名称'])
            ->addColumn('url','string',['comment'=>'导航连接地址'])
            ->addColumn('status','integer',['comment'=>'导航状态0-正常显示;1-隐藏'])
            ->addColumn('sort','integer',['comment'=>'排序'])
            ->addColumn('nav_type','integer',['comment'=>'导航类型;0-自定义;1-分类导航'])
            ->addColumn('article_cate_id','integer',['comment'=>'文章分类id'])
            ->addTimestamps()
            ->addSoftDelete()
            ->create();

    }
    public function up()
    {
        parent::up(); // TODO: Change the autogenerated stub
    }
    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
