<?php

use think\migration\Migrator;
use think\migration\db\Column;
use Phinx\Db\Adapter\MysqlAdapter;

class Pages extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */
    public function change()
    {
        $table=$this->table('pages',['collation'=>'utf8_unicode_ci']);
        $table->addColumn('title','string',['comment'=>'页面标题'])
            ->addColumn('link_alias','string',['comment'=>'连接别名'])
            ->addColumn('keyword','string',['comment'=>'keywords'])
            ->addColumn('desc','string',['comment'=>'描述'])
            ->addColumn('content','text',['limit'=>MysqlAdapter::TEXT_LONG,'comment'=>'页面markdown格式'])
            ->addColumn('html_content','text',['limit'=>MysqlAdapter::TEXT_LONG,'comment'=>'html页面内容'])
            ->addTimestamps()
            ->addSoftDelete()
            ->create();

    }
    public function up()
    {
        parent::up(); // TODO: Change the autogenerated stub
    }
    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
