<?php

use think\migration\Migrator;
use think\migration\db\Column;
use Phinx\Db\Adapter\MysqlAdapter;

class Articles extends Migrator
{
    /**
     * Change Method.
     *
     * Write your reversible migrations using this method.
     *
     * More information on writing migrations is available here:
     * http://docs.phinx.org/en/latest/migrations.html#the-abstractmigration-class
     *
     * The following commands can be used in this method and Phinx will
     * automatically reverse them when rolling back:
     *
     *    createTable
     *    renameTable
     *    addColumn
     *    renameColumn
     *    addIndex
     *    addForeignKey
     *
     * Remember to call "create()" or "update()" and NOT "save()" when working
     * with the Table class.
     */

    /**
     * Migrate Method
     * Version 1.1
     * Creator By River
     * 2018-09-19 18:24:31
     */
    public function change()
    {
        //create the table

        $table=$this->table('articles',['collation'=>'utf8_unicode_ci']);
        $table->addColumn('title','string',['default'=>'','comment'=>'文章标题'])
            ->addColumn('keyword','string',['default'=>'','comment'=>'keywords'])
            ->addColumn('desc','string',['default'=>'','comment'=>'描述'])
            ->addColumn('content','text',['limit'=>MysqlAdapter::TEXT_LONG,'comment'=>'文章内容,markdown格式'])
            ->addColumn('user_id','integer',['comment'=>'文章编写人,对应users表','default'=>0])
            ->addColumn('cate_id','integer',['comment'=>'文章分类','default'=>0])
            ->addColumn('comment_count','integer',['comment'=>'评论数','default'=>0])
            ->addColumn('read_count','integer',['comment'=>'阅读数','default'=>0])
            ->addColumn('status','integer',['limit'=>MysqlAdapter::INT_TINY,'comment'=>'文章状态：0-公开;1-私密','default'=>0])
            ->addColumn('sort','integer',['default'=>0,'comment'=>'排序'])
            ->addColumn('html_content','text',['limit'=>MysqlAdapter::TEXT_LONG,'comment'=>'文章内容,html格式'])
            ->addTimestamps()
            ->addSoftDelete()
            ->addIndex(['title','user_id','cate_id'])
            ->create();
    }

    /**
     * Migrate Up
     * Version 1.1
     * Creator By River
     * 2018-09-19 18:23:42
     */
    public function up()
    {
        parent::up(); // TODO: Change the autogenerated stub
    }

    /**
     * Migrate Down
     * Version 1.1
     * Creator By River
     * 2018-09-19 18:24:06
     */
    public function down()
    {
        parent::down(); // TODO: Change the autogenerated stub
    }
}
